### ISSUE TITLE
ERROR: Service 'tls_apiui' failed to build

### ISSUE THREAD

**Issue by cheebinc** [intel/Training-and-Learning-Suite#15]
Failed to install while running './setup_TLS_docker.sh'

Full error logs:
ERROR: Service 'tls_apiui' failed to build: The command '/bin/sh -c  cd ${HOME}/webservice/ui && npm install' returned a non-zero code: 1

**Comment by mjasamai** [comment]
This issue due to one of the NPM package being remove, resolved in the latest code.
